"""
model.py -- matching model + F_0.5-aware decision layer.

MODEL CHOICE
------------
LightGBM (MIT licence, satisfies the competition's MIT/Apache-2.0 model rule;
a GBDT has no "parameters" in the 8B sense so the size cap is moot). Reasons it
is the right tool rather than a neural matcher:
  * the features are heterogeneous, tabular, and already highly informative;
  * it trains on tens of millions of pairs on CPU in minutes with n_jobs=-1;
  * it is monotone-friendly and its probabilities calibrate well, which matters
    because the entire decision layer is a threshold on those probabilities.
`benchmark_models` is provided so the choice is made on YOUR validation numbers
rather than on this assertion -- run it before committing.

HARD NEGATIVES
--------------
Random negatives are useless here: a random S2 record shares nothing with the
query and the model learns a trivial boundary. The negatives that matter are
exactly the ones blocking retrieves -- same postal code different business,
near-identical name different address, shared rare token different entity. So
training pairs are generated by running the REAL blocking pipeline over
training queries and labelling whatever it returns. The model therefore trains
on precisely the distribution it will see at inference. This also means the
hard-negative strategy needs no separate mining code -- blocking IS the miner.

DECISION LAYER
--------------
F_0.5 weights precision 2x. The optimiser below maximises the true competition
metric (macro F_0.5 over S1 entities, singletons included) directly, rather
than pairwise F1 or AUC, and searches coarse-then-fine. Two optional extras --
a top-score margin rule and the global-uniqueness pass -- are gated behind
measured validation gains.
"""
import numpy as np

try:
    import lightgbm as lgb
except ImportError:
    lgb = None

from metrics import macro_f05


# ---------------------------------------------------------------- training
def train_lightgbm(X, y, groups=None, params=None, num_round=600, seed=0):
    if lgb is None:
        raise ImportError("pip install lightgbm")
    p = dict(
        objective="binary",
        metric="binary_logloss",
        learning_rate=0.05,
        num_leaves=127,
        min_data_in_leaf=100,
        feature_fraction=0.85,
        bagging_fraction=0.85,
        bagging_freq=1,
        lambda_l2=1.0,
        num_threads=-1,
        verbose=-1,
        seed=seed,
        deterministic=True,      # reproducibility (Part 27)
        force_row_wise=True,
    )
    p.update(params or {})
    ds = lgb.Dataset(X, label=y, free_raw_data=False)
    return lgb.train(p, ds, num_boost_round=num_round)


def benchmark_models(Xtr, ytr, Xva, yva, truth, va_index, seed=0):
    """Compare candidate matchers on the REAL metric. Do not skip this."""
    out = {}
    if lgb is not None:
        m = train_lightgbm(Xtr, ytr, seed=seed)
        out["lightgbm"] = m
    try:
        import xgboost as xgb
        clf = xgb.XGBClassifier(
            n_estimators=600, max_depth=8, learning_rate=0.05,
            subsample=0.85, colsample_bytree=0.85, reg_lambda=1.0,
            tree_method="hist", n_jobs=-1, random_state=seed,
            eval_metric="logloss")
        clf.fit(Xtr, ytr)
        out["xgboost"] = clf
    except ImportError:
        pass
    try:
        from catboost import CatBoostClassifier
        cb = CatBoostClassifier(
            iterations=600, depth=8, learning_rate=0.05, l2_leaf_reg=3.0,
            random_seed=seed, verbose=0, thread_count=-1)
        cb.fit(Xtr, ytr)
        out["catboost"] = cb
    except ImportError:
        pass
    return out


def predict(model, X):
    if hasattr(model, "predict_proba"):
        return model.predict_proba(X)[:, 1]
    return model.predict(X)


# ------------------------------------------------------- decision / F_0.5
def assemble(preds, va_index, threshold, margin=None):
    """preds: P(match) per candidate row. va_index: list of (s1_id, cand_id).

    Emits the empty set for an S1 entity when nothing clears the threshold --
    singleton prediction is a first-class outcome worth a full 1.0 on the
    metric, not a failure mode.
    """
    by_q = {}
    for (s1, cid), p in zip(va_index, preds):
        by_q.setdefault(s1, []).append((cid, p))
    out = {}
    for s1, lst in by_q.items():
        keep = {cid for cid, p in lst if p >= threshold}
        if margin is not None and keep:
            top = max(p for _, p in lst)
            keep = {cid for cid, p in lst if p >= threshold and p >= top - margin}
        out[s1] = keep
    return out


def optimise_threshold(preds, va_index, truth, margins=(None,), verbose=True):
    """Maximise the real macro F_0.5. Coarse sweep, then fine around the best."""
    best = (-1.0, None, None)
    coarse = np.arange(0.30, 0.96, 0.05)
    for mg in margins:
        for th in coarse:
            sc = macro_f05(truth, assemble(preds, va_index, th, mg))["macro_f05"]
            if sc > best[0]:
                best = (sc, float(th), mg)
    lo = max(0.05, best[1] - 0.05)
    hi = min(0.99, best[1] + 0.05)
    for mg in margins:
        for th in np.arange(lo, hi, 0.005):
            sc = macro_f05(truth, assemble(preds, va_index, th, mg))["macro_f05"]
            if sc > best[0]:
                best = (sc, float(th), mg)
    if verbose:
        print(f"  best macro_F0.5={best[0]:.5f} @ threshold={best[1]:.3f} "
              f"margin={best[2]}")
    return best


def apply_global_uniqueness(preds, va_index, threshold):
    """Exploit a hard structural fact found in the audit: in the training
    ground truth, NO S2/S3 record is ever matched to more than one S1 entity
    (checked exhaustively over all 7,638,365 match edges -- zero violations).

    So if two S1 entities both claim the same S2/S3 record, at most one is
    right. Award it to the higher-scoring claimant and drop the other. This is
    pure precision gain, which is the expensive side of F_0.5.

    VALIDATE before enabling: measure with and without on your own fold.
    """
    claims = {}
    for (s1, cid), p in zip(va_index, preds):
        if p < threshold:
            continue
        cur = claims.get(cid)
        if cur is None or p > cur[1]:
            claims[cid] = (s1, p)
    out = {}
    for cid, (s1, _) in claims.items():
        out.setdefault(s1, set()).add(cid)
    for s1, _ in va_index:
        out.setdefault(s1, set())
    return out
